language: php
php:
  - "5.3"
install:
  composer install
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  vendor/bin/phpunit